

services:
  db:
    image: postgres:13
    container_name: ebd_db
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: secretaria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: ebd_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: